#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

function usage {
    echo "Usage:"
    grep -E '\)[[:space:]]+# ' "${SELF}"
    exit
}

function update {
    # update the list of packages
    sudo nix-channel --update

    # upgrade system packages
    sudo nixos-rebuild boot

    # upgrade user packages
    nix-env -u --always
}

function cleanup {
    # remove the indirect GC (Garbage Collection) roots
    # (e.g. generated by nix-build)
    sudo rm /nix/var/nix/gcroots/auto/*

    # delete old generations of all profiles (-d), then collect garbage
    sudo nix-collect-garbage -d

    # delete old generations of the user profiles
    nix-collect-garbage -d
}

function rebuild {
    rm -f /home/pherseus/.xmonad/xmonad-x86_64-linux

    sudo nixos-rebuild switch
}

SELF="${0}"

if [ "$#" -ne 1 ]; then
    usage
fi

action="${1}"
shift

case "${action}" in
    u|update )           # Update the system
        update
    ;;

    c|cleanup )          # Cleanup the system
        cleanup
    ;;

    r|rebuild )          # rebuild the system
        rebuild
    ;;

    *)
        usage
esac
